=== aichingm/ReadlineTemplate/src/ReadlineTemplate/Template.xsd
<?xml version="1.0"?>
<!--

If your Template.xml file is valid aginst this schema there should be no problem at running it 

-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="Template">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element name="Text">
                    <xs:complexType>
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="defaultGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="Number">
                    <xs:complexType>
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="defaultGroup" />
                        <xs:attributeGroup ref="minMaxGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="Integer">
                    <xs:complexType>
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="defaultGroup" />
                        <xs:attributeGroup ref="minMaxGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="Hidden">
                    <xs:complexType>
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="defaultGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="File">
                    <xs:complexType>
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="fileGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="ListChoice">
                    <xs:complexType>
                        <xs:group ref="ListGroup" />
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="NamedListChoice">
                    <xs:complexType>
                        <xs:group ref="NamedListGroup" />
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="minMaxGroup" />
                        <xs:attributeGroup ref="separatorGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="MultiListChoice">
                    <xs:complexType>
                        <xs:group ref="ListGroup" />
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                        <xs:attributeGroup ref="minMaxGroup" />
                        <xs:attributeGroup ref="separatorGroup" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="Boolean">
                    <xs:complexType>
                        <xs:attributeGroup ref="mustHaveGroup" />
                        <xs:attributeGroup ref="dependsGroup" />
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:group name="ListGroup">
        <xs:sequence>
            <xs:element name="Item"  maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="NamedListGroup">
        <xs:sequence>
            <xs:element name="Item"  maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                    <xs:attribute name="text" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:attributeGroup name="fileGroup">
        <xs:attribute name="exists" use="required" type="xs:string"/>
        <xs:attribute name="extension" use="optional" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dependsGroup">
        <xs:attribute name="depends" use="optional" type="xs:string" />
        <xs:attribute name="depends-equals" use="optional" type="xs:string" />
    </xs:attributeGroup>
    <xs:attributeGroup name="minMaxGroup">
        <xs:attribute name="min" use="optional" type="xs:int" />
        <xs:attribute name="max" use="optional" type="xs:int" />
    </xs:attributeGroup>
    <xs:attributeGroup name="mustHaveGroup"> 
        <xs:attribute name="key" type="xs:string" />
        <xs:attribute name="prompt" type="xs:string" />
        <xs:attribute name="exclude">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="from-data"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:attributeGroup name="defaultGroup">
        <xs:attribute name="default" use="optional" type="xs:string" />
    </xs:attributeGroup>
    <xs:attributeGroup name="separatorGroup">
        <xs:attribute name="separator" type="xs:string" />
    </xs:attributeGroup>
</xs:schema>

=== aichingm/ReadlineTemplate/examples/Template.xml
<?xml version="1.0" encoding="UTF-8"?>
<Template
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation="../src/ReadlineTemplate/Template.xsd">
    <!-- admin -->
    <Text key="_admin_password" prompt="Password for user admin: " default="admin" exclude="from-data"/>
    <!-- database -->
    <ListChoice key="database_type" prompt="Select the type of database you want to use: ">
        <Item value="mysql"/>
        <Item value="sqlite"/>
    </ListChoice>
    <!-- mysql -->
    <Text key="database_mysql_server" prompt="Mysql server [localhost]: " default="localhost" depends="database_type" depends-equals="mysql" />
    <Text key="database_mysql_username" prompt="Mysql username: " depends="database_type" depends-equals="mysql" />
    <Text key="database_mysql_password" prompt="Mysql password: " depends="database_type" depends-equals="mysql" />
    <Text key="database_database" prompt="Mysql database name: " depends="database_type" depends-equals="mysql" />
    <Text key="database_table_prefix" prompt="Mysql table prefix: " depends="database_type" depends-equals="mysql" />
    <Boolean key="_mysql_renew_database" prompt="Delete existing database: " exclude="from-data" depends="database_type" depends-equals="mysql" />
    <Boolean key="_mysql_renew_table" prompt="Delete existing tables " exclude="from-data" depends="_mysql_renew_database" depends-equals="false" />
    <!-- sqlite -->
    <Text key="database_sqlite_path" prompt="Sqlite file: " depends="database_type" depends-equals="sqlite" />
    <Text key="database_table_prefix" prompt="Sqlite table prefix: " depends="database_type" depends-equals="sqlite" />
    <Hidden key="database_database" prompt="" default="main" depends="database_type" depends-equals="sqlite" />
    <Boolean key="_sqlite_renew_database" prompt="Overwrite file if existing" exclude="from-data" depends="database_type" depends-equals="sqlite" />
    <Boolean key="_sqlite_renew_table" prompt="Overwrite tables if existing" exclude="from-data" depends="_sqlite_renew_database" depends-equals="false" />
    <!-- api version -->
    <ListChoice key="api_version" prompt="Select the api version you want to use: ">
        <Item value="1" />
        <Item value="2"/>
    </ListChoice>
</Template>
